Repository CPJKU/partitura, pull requests merged in 2022-10, with the labels that each got.

#156 Fix for Read The Docs Documentation Page
  .readthedocs.yml
  README.md
  docs/Makefile
  docs/make.bat
  docs/requirements.txt
  docs/source/Tutorial/notebook.ipynb
  docs/source/conf.py
  docs/source/genindex.rst
  docs/source/images/aknowledge_logo.png
  docs/source/images/aknowledge_logo_negative.png
  docs/source/images/erc_fwf_logos.jpg
  docs/source/images/score_example.png
  docs/source/images/score_example_1.png
  docs/source/images/score_example_2.png
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/modules/partitura.musicanalysis.rst
  docs/source/modules/partitura.performance.rst
  docs/source/modules/partitura.rst
  docs/source/modules/partitura.score.rst
  docs/source/modules/partitura.utils.rst
  setup.py
Labels: bug, documentation

#160 Kern import fix
  partitura/io/importkern.py
  partitura/io/importmusicxml.py
  partitura/score.py
  partitura/utils/music.py
Labels: bug

#168 Declare encoding and add/update docstrings at the top of each module
  partitura/__init__.py
  partitura/directions.py
  partitura/display.py
  partitura/io/__init__.py
  partitura/io/exportaudio.py
  partitura/io/exportmatch.py
  partitura/io/exportmidi.py
  partitura/io/exportmusicxml.py
  partitura/io/importkern.py
  partitura/io/importmei.py
  partitura/io/importmidi.py
  partitura/io/importmusicxml.py
  partitura/io/importnakamura.py
  partitura/io/musescore.py
  partitura/musicanalysis/__init__.py
  partitura/musicanalysis/key_identification.py
  partitura/musicanalysis/meter.py
  partitura/musicanalysis/note_features.py
  partitura/musicanalysis/performance_codec.py
  partitura/musicanalysis/pitch_spelling.py
  partitura/musicanalysis/tonal_tension.py
  partitura/musicanalysis/voice_separation.py
  partitura/performance.py
  partitura/score.py
  partitura/utils/__init__.py
  partitura/utils/generic.py
  partitura/utils/misc.py
  partitura/utils/music.py
  partitura/utils/synth.py
  tests/__init__.py
  tests/test_deprecations.py
  tests/test_kern.py
  tests/test_key_estimation.py
  tests/test_load_performance.py
  tests/test_load_score.py
  tests/test_match_import.py
  tests/test_mei.py
  tests/test_merge_parts.py
  tests/test_metrical_position.py
  tests/test_midi_export.py
  tests/test_midi_import.py
  tests/test_nakamura.py
  tests/test_new_divs.py
  tests/test_note_array.py
  tests/test_note_features.py
  tests/test_parangonada.py
  tests/test_part_properties.py
  tests/test_performance.py
  tests/test_performance_codec.py
  tests/test_pianoroll.py
  tests/test_pitch_spelling.py
  tests/test_quarter_adjust.py
  tests/test_rest_array.py
  tests/test_synth.py
  tests/test_time_estimation.py
  tests/test_times.py
  tests/test_tonal_tension.py
  tests/test_utils.py
  tests/test_voice_estimation.py
  tests/test_xml.py
Labels: documentation

#167 Fix issue #166 (synthesizing scores with pickup measures)
  partitura/io/exportaudio.py
  partitura/utils/music.py
  partitura/utils/synth.py
  tests/test_synth.py
  tests/test_utils.py
Labels: bug
