Repository CPJKU/partitura, pull requests merged in 2023-05, with the labels that each got.

#228 Fix issue #227
  partitura/score.py
  tests/__init__.py
  tests/data/musicxml/test_ts_map_ts_starts_not_at_zero.xml
  tests/test_metrical_position.py
Labels: bug

#237 Fix Issue #180
  partitura/utils/synth.py
  tests/test_synth.py
Labels: bug

#236 Issues with temporary directory on Windows for testing PIL
  tests/test_display.py
Labels: bug

#199 Add new util: Slice PerformedPart by time
  partitura/utils/music.py
Labels: enhancement

#233 performance codec fix
  partitura/musicanalysis/performance_codec.py
  tests/test_performance_codec.py
Labels: enhancement

#242 add test for slice_ppart_by_time; minor formatting of function
  partitura/utils/music.py
  tests/test_utils.py
Labels: documentation

#226 Roman Numeral Analysis add on (Reopen #220 after reverting merge)
  partitura/io/exportmusicxml.py
  partitura/io/importmusicxml.py
  partitura/score.py
  partitura/utils/music.py
  tests/__init__.py
  tests/data/musicxml/example_octave_shift.musicxml
  tests/data/musicxml/test_harmony.musicxml
  tests/test_harmony.py
  tests/test_octave_shift.py
  tests/test_transpose.py
Labels: enhancement
