Repository CPJKU/partitura, pull requests merged in 2023-09, with the labels that each got.

#314 Load_score select the correct parser based on the file extension
  partitura/io/__init__.py
Labels: enhancement

#308 bugfix for midi scores with ts only in one track
  partitura/io/importmidi.py
  tests/__init__.py
  tests/data/midi/bach_midi_score.mid
  tests/test_midi_import.py
Labels: bug

#317 A unit test example for cross staff beaming for musicxml
  tests/data/musicxml/test_cross_staff_beaming.musicxml
  tests/test_cross_staff_beaming.py
Labels: documentation

#303 new score attributes in match export, new score properties, misc fixes
  partitura/directions.py
  partitura/io/exportmatch.py
  partitura/io/exportmidi.py
  partitura/io/importmidi.py
  partitura/io/importmusicxml.py
  partitura/io/matchfile_utils.py
  partitura/io/matchlines_v1.py
  partitura/score.py
  tests/__init__.py
  tests/data/match/mozart_k265_var1.match
  tests/data/musicxml/test_score_object.musicxml
  tests/test_match_import.py
  tests/test_pianoroll.py
  tests/test_tonal_tension.py
  tests/test_xml.py
Labels: enhancement
