Repository CPJKU/partitura, pull requests merged in 2024-07, with the labels that each got.

#345 Dcml annotation parser
  .github/workflows/partitura_unittests.yml
  partitura/__init__.py
  partitura/directions.py
  partitura/io/__init__.py
  partitura/io/exportmusicxml.py
  partitura/io/importdcml.py
  partitura/io/importmusicxml.py
  partitura/musicanalysis/key_identification.py
  partitura/musicanalysis/meter.py
  partitura/score.py
  partitura/utils/globals.py
  partitura/utils/music.py
  partitura/utils/normalize.py
  partitura/utils/synth.py
  tests/__init__.py
  tests/data/tsv/test_harmonies.tsv
  tests/data/tsv/test_measures.tsv
  tests/data/tsv/test_notes.tsv
  tests/test_dcml_import.py
Labels: enhancement

#360 fix issue 358
  partitura/musicanalysis/performance_codec.py
Labels: bug

#362 improve documentation performance note_array
  partitura/performance.py
Labels: documentation
